module.exports.profilesController = require('./profilesController')
module.exports.articlesController = require('./postsController')
module.exports.commentsController = require('./commentsController')
module.exports.categoriesController = require()
module.exports.keywordsController = require()